//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtoservis.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user80_dbEntities : DbContext
    {
        public user80_dbEntities()
            : base("name=user80_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dm_Avtomobili> dm_Avtomobili { get; set; }
        public virtual DbSet<dm_Defekti> dm_Defekti { get; set; }
        public virtual DbSet<dm_Detali> dm_Detali { get; set; }
        public virtual DbSet<dm_Detali_v_zakaze> dm_Detali_v_zakaze { get; set; }
        public virtual DbSet<dm_Foto_v_zakaze> dm_Foto_v_zakaze { get; set; }
        public virtual DbSet<dm_Gruppi_avto> dm_Gruppi_avto { get; set; }
        public virtual DbSet<dm_Komplektacii_avto> dm_Komplektacii_avto { get; set; }
        public virtual DbSet<dm_Marki_avto> dm_Marki_avto { get; set; }
        public virtual DbSet<dm_Modeli_avto> dm_Modeli_avto { get; set; }
        public virtual DbSet<dm_Proizvoditeli> dm_Proizvoditeli { get; set; }
        public virtual DbSet<dm_Rabochie_mesta> dm_Rabochie_mesta { get; set; }
        public virtual DbSet<dm_Raboti> dm_Raboti { get; set; }
        public virtual DbSet<dm_Raboti_v_zakaze> dm_Raboti_v_zakaze { get; set; }
        public virtual DbSet<dm_Roli> dm_Roli { get; set; }
        public virtual DbSet<dm_Strani> dm_Strani { get; set; }
        public virtual DbSet<dm_Tipi_detalei> dm_Tipi_detalei { get; set; }
        public virtual DbSet<dm_Tipi_dvigatelya> dm_Tipi_dvigatelya { get; set; }
        public virtual DbSet<dm_Tipi_korobki_peredach> dm_Tipi_korobki_peredach { get; set; }
        public virtual DbSet<dm_Tipi_kuzova> dm_Tipi_kuzova { get; set; }
        public virtual DbSet<dm_Tipi_privoda> dm_Tipi_privoda { get; set; }
        public virtual DbSet<dm_Users> dm_Users { get; set; }
        public virtual DbSet<dm_Uzli_avto> dm_Uzli_avto { get; set; }
        public virtual DbSet<dm_Zakazi> dm_Zakazi { get; set; }
    }
}
