//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtoservis.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media.Imaging;

    public partial class dm_Avtomobili
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dm_Avtomobili()
        {
            this.dm_Zakazi = new HashSet<dm_Zakazi>();
        }
    
        public int ID_avtomobilya { get; set; }
        public int Model { get; set; }
        public string WIN_nomer { get; set; }
        public int Vladelec { get; set; }
        public string Gos_nomer { get; set; }

        public BitmapImage FotoImage { get; set; }

        public virtual dm_Komplektacii_avto dm_Komplektacii_avto { get; set; }
        public virtual dm_Users dm_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dm_Zakazi> dm_Zakazi { get; set; }
    }
}
