//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtoservis.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_Defekti
    {
        public int ID_defekta { get; set; }
        public Nullable<int> Uzel_avto { get; set; }
        public string Opisanie { get; set; }
        public string Rekomendacii { get; set; }
        public string Primechaniya { get; set; }
        public Nullable<int> Zakaz { get; set; }
    
        public virtual dm_Uzli_avto dm_Uzli_avto { get; set; }
        public virtual dm_Zakazi dm_Zakazi { get; set; }
    }
}
