//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtoservis.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_Detali
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dm_Detali()
        {
            this.dm_Detali_v_zakaze = new HashSet<dm_Detali_v_zakaze>();
        }
    
        public int ID_detali { get; set; }
        public string Nazvanie { get; set; }
        public int Tip { get; set; }
        public int Proizvoditel { get; set; }
        public decimal Cena { get; set; }
        public string Foto { get; set; }
        public string Opisanie { get; set; }
    
        public virtual dm_Proizvoditeli dm_Proizvoditeli { get; set; }
        public virtual dm_Tipi_detalei dm_Tipi_detalei { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dm_Detali_v_zakaze> dm_Detali_v_zakaze { get; set; }
    }
}
