//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtoservis.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_Foto_v_zakaze
    {
        public int ID_foto_v_zakaze { get; set; }
        public int ID_zakaza { get; set; }
        public string Foto { get; set; }
    
        public virtual dm_Zakazi dm_Zakazi { get; set; }
    }
}
