//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtoservis.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media.Imaging;

    public partial class dm_Marki_avto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dm_Marki_avto()
        {
            this.dm_Modeli_avto = new HashSet<dm_Modeli_avto>();
        }
    
        public int ID_marki { get; set; }
        public string Nazvanie_marki { get; set; }
        public int Gruppa { get; set; }
        public int Strana_proizvoditel { get; set; }
        public string Logotip { get; set; }

        public BitmapImage LogotipImage { get; set; }

        public virtual dm_Gruppi_avto dm_Gruppi_avto { get; set; }
        public virtual dm_Strani dm_Strani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dm_Modeli_avto> dm_Modeli_avto { get; set; }
    }
}
