//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtoservis.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_Modeli_avto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dm_Modeli_avto()
        {
            this.dm_Komplektacii_avto = new HashSet<dm_Komplektacii_avto>();
        }
    
        public int ID_modeli_avto { get; set; }
        public string Model { get; set; }
        public int Marka { get; set; }
        public int God_vipuska { get; set; }
        public Nullable<int> God_okonchaniya_vipuska { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dm_Komplektacii_avto> dm_Komplektacii_avto { get; set; }
        public virtual dm_Marki_avto dm_Marki_avto { get; set; }
    }
}
