//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtoservis.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_Raboti_v_zakaze
    {
        public int ID_raboti_v_zakaze { get; set; }
        public int ID_zakaza { get; set; }
        public int ID_raboti { get; set; }
        public Nullable<decimal> Zakrep_stoimost { get; set; }
    
        public virtual dm_Raboti dm_Raboti { get; set; }
        public virtual dm_Zakazi dm_Zakazi { get; set; }
    }
}
