//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtoservis.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_Uzli_avto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dm_Uzli_avto()
        {
            this.dm_Defekti = new HashSet<dm_Defekti>();
        }
    
        public int ID_uzla_avto { get; set; }
        public string Nazvanie_uzla_avto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dm_Defekti> dm_Defekti { get; set; }
    }
}
