//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtoservis.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dm_Users()
        {
            this.dm_Avtomobili = new HashSet<dm_Avtomobili>();
            this.dm_Zakazi = new HashSet<dm_Zakazi>();
            this.dm_Zakazi1 = new HashSet<dm_Zakazi>();
        }
    
        public int ID_user { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }

        public string FullName => $"{this.Familiya ?? ""} {this.Imya ?? ""} {this.Otchestvo ?? ""}".Trim();

        public System.DateTime Data_rojdeniya { get; set; }
        public Nullable<int> Stazh { get; set; }
        public int Rol { get; set; }
        public string Foto { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Nomer_telefona { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dm_Avtomobili> dm_Avtomobili { get; set; }
        public virtual dm_Roli dm_Roli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dm_Zakazi> dm_Zakazi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dm_Zakazi> dm_Zakazi1 { get; set; }
    }
}
