//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avtoservis.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_Zakazi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dm_Zakazi()
        {
            this.dm_Defekti = new HashSet<dm_Defekti>();
            this.dm_Detali_v_zakaze = new HashSet<dm_Detali_v_zakaze>();
            this.dm_Foto_v_zakaze = new HashSet<dm_Foto_v_zakaze>();
            this.dm_Raboti_v_zakaze = new HashSet<dm_Raboti_v_zakaze>();
        }

        // Добавьте это свойство в partial класс
        public string ClientFullName => dm_Users1?.FullName ?? "Не указан";

        public string AcceptedClosedDates =>
    $"{Data_i_vremya_priema_avto:dd.MM.yyyy HH:mm} - {Data_i_vremya_vidachi_avto:dd.MM.yyyy HH:mm}";

        public int ID_zakaza { get; set; }
        public System.DateTime Data_sozdaniya { get; set; }
        public string Status { get; set; }
        public int Klient { get; set; }
        public Nullable<int> Ispolnitel { get; set; }
        public System.DateTime Data_i_vremya_priema_avto { get; set; }
        public int Rabochee_mesto { get; set; }
        public Nullable<int> Avtomobil { get; set; }
        public bool Oplata { get; set; }

        public decimal Summa { get; set; }
        public System.DateTime Data_i_vremya_vidachi_avto { get; set; }


        public decimal TotalSum { get; set; }

        public virtual dm_Avtomobili dm_Avtomobili { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dm_Defekti> dm_Defekti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dm_Detali_v_zakaze> dm_Detali_v_zakaze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dm_Foto_v_zakaze> dm_Foto_v_zakaze { get; set; }
        public virtual dm_Rabochie_mesta dm_Rabochie_mesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dm_Raboti_v_zakaze> dm_Raboti_v_zakaze { get; set; }
        public virtual dm_Users dm_Users { get; set; }
        public virtual dm_Users dm_Users1 { get; set; }
    }
}
